export const verificarStatus = [{
    status: 'DISPONIVEL',
    desc: 'Disponível',
    permiteEdicao: true,
    permiteIncluirDocumento: false,
    permiteEnvioCv: false,
    permiteAssumir: false,
    permiteAprovar: false,
    permiteRecusa: false,
    permiteEmitir: false,
    permiteRevogar: false,
    permiteVisualizarDocumentos: true
},
{
    status: 'VALIDACAO',
    desc: 'Validação',
    permiteEdicao: true,
    permiteIncluirDocumento: true,
    permiteEnvioCv: true,
    permiteAssumir: false,
    permiteAprovar: false,
    permiteRecusa: false,
    permiteEmitir: false,
    permiteRevogar: false,
    permiteVisualizarDocumentos: true
},
{
    status: 'ENVIADOCV',
    desc: 'Enviado cv',
    permiteEdicao: false,
    permiteIncluirDocumento: false,
    permiteEnvioCv: false,
    permiteAssumir: true,
    permiteAprovar: false,
    permiteRecusa: false,
    permiteEmitir: false,
    permiteRevogar: false,
    permiteVisualizarDocumentos: true
},
{
    status: 'ANALISE',
    desc: 'Análise',
    permiteEdicao: false,
    permiteIncluirDocumento: false,
    permiteEnvioCv: false,
    permiteAssumir: false,
    permiteAprovar: true,
    permiteRecusa: true,
    permiteEmitir: false,
    permiteRevogar: false,
    permiteVisualizarDocumentos: true
},
{
    status: 'REPROVADO',
    desc: 'Reprovado',
    permiteEdicao: true,
    permiteIncluirDocumento: true,
    permiteEnvioCv: true,
    permiteAssumir: false,
    permiteAprovar: false,
    permiteRecusa: false,
    permiteEmitir: false,
    permiteRevogar: false,
    permiteVisualizarDocumentos: true
},
{
    status: 'APROVADO',
    desc: 'Aprovado',
    permiteEdicao: false,
    permiteIncluirDocumento: false,
    permiteEnvioCv: false,
    permiteAssumir: false,
    permiteAprovar: false,
    permiteRecusa: false,
    permiteEmitir: true,
    permiteRevogar: false,
    permiteVisualizarDocumentos: true
},
{
    status: 'EMITIDO',
    desc: 'Emitido',
    permiteEdicao: false,
    permiteIncluirDocumento: false,
    permiteEnvioCv: false,
    permiteAssumir: false,
    permiteAprovar: false,
    permiteRecusa: false,
    permiteEmitir: false,
    permiteRevogar: true,
    permiteVisualizarDocumentos: true
}, {
    status: 'EM REVOGACAO',
    desc: 'Em revogação',
    permiteEdicao: false,
    permiteIncluirDocumento: true,
    permiteEnvioCv: false,
    permiteAssumir: false,
    permiteAprovar: false,
    permiteRecusa: false,
    permiteEmitir: false,
    permiteRevogar: false,
    permiteVisualizarDocumentos: true
},
{
    status: 'REVOGADO',
    desc: 'Revogado',
    permiteEdicao: false,
    permiteIncluirDocumento: false,
    permiteEnvioCv: false,
    permiteAssumir: false,
    permiteAprovar: false,
    permiteRecusa: false,
    permiteEmitir: false,
    permiteRevogar: false,
    permiteVisualizarDocumentos: true
}
]